### ISSUE TITLE
Is this code open source?

### ISSUE THREAD

**Issue by rparrett** [rust-adventure/bevy-examples#1]
This seems like a great little resource for Bevy shaders. Unfortunately, there's no license specified, so it's not clear whether the code can actually be used or redistributed.

**Comment by ChristopherBiscardi** [comment]
yes, I'll add a license.

**Comment by ChristopherBiscardi** [comment]
I've added the same licensing scheme as Bevy.

https://github.com/rust-adventure/bevy-examples/commit/e93138090d6c1e79774d871ac028374e660ba42b

**Comment by rparrett** [comment]
Thanks!
