### ISSUE TITLE
Bevy 13: Shader changes

### ISSUE THREAD

**Issue by Stay1444** [rust-adventure/bevy-examples#14]
- Custom 2d and 3d mesh/material shaders should now use bind group 2 @group(2) @binding(x) for their bound resources, instead of bind group 1.
- Many internal pieces of rendering code have changed so that mesh data is now in bind group 1, and material data is now in bind group 2. Semi-custom rendering setups (that don’t use the Material or Material2d APIs) should adapt to these changes.

[Migrating from 0.12 to 0.13](https://bevyengine.org/learn/migration-guides/0-12-to-0-13/)

**Comment by ChristopherBiscardi** [comment]
thanks for the issue!

The fix for #13 hasn't been released yet (will go out in 0.13.1), but otherwise everything should upgrade smoothly.

**Comment by ChristopherBiscardi** [comment]
The globals change went out in the recent 0.13.1, so upgrading can proceed now. I've already started by publishing bevy_shader_utils 0.7 which is 0.13-compatible

**Comment by ChristopherBiscardi** [comment]
closing in favor of #16
