### ISSUE TITLE
ShaderUtilsPlugin causing error 

### ISSUE THREAD

**Issue by MaybeMaebh** [rust-adventure/bevy-examples#15]
"the trait bound `(bevy::DefaultPlugins, ShaderUtilsPlugin, PlayerPlugin, camera::CameraPlugin, WorldPlugin, bevy_third_person_camera::ThirdPersonCameraPlugin, bevy_inspector_egui::quick::WorldInspectorPlugin, bevy::prelude::MaterialPlugin<ExtendedMaterial<bevy::prelude::StandardMaterial, ExtensionTest>>): bevy_app::plugin::sealed::Plugins<_>` is not satisfied
perhaps two different versions of crate `bevy_app` are being used?"
 is being reported whenever I add the ShaderUtilsPlugin, this maybe be my fault as I am new to bevy and rust. I'm using bevy 0.13.1.

Much thanks Maebh!

**Comment by ChristopherBiscardi** [comment]
I just published [`bevy_shader_utils 0.7`](https://docs.rs/bevy_shader_utils/latest/bevy_shader_utils/) which is compatible with bevy 0.13 and confirmed it worked in a new project.

Please upgrade to 0.7 for 0.13.

<img width="844" alt="Screenshot 2024-03-26 at 11 53 41 AM" src="https://github.com/rust-adventure/bevy-examples/assets/551247/62c6cdd8-ba32-4cf0-9870-b6be5690d0cc">
