### ISSUE TITLE
i have multiple prob with "cargo run --example voronoise-pan"

### ISSUE THREAD

**Issue by syapk** [rust-adventure/bevy-examples#6]
error[E0609]: no field `time` on type `&mut CustomMaterial`
  --> libs\bevy_shader_utils\examples\voronoise-pan.rs:62:20
   |
62 |         material.1.time =
   |                    ^^^^ unknown field
   |
   = note: available fields are: `color`

error[E0599]: no method named `seconds_since_startup` found for struct `bevy::prelude::Res<'_, bevy::prelude::Time>` in the current scope
  --> libs\bevy_shader_utils\examples\voronoise-pan.rs:63:18
   |
63 |             time.seconds_since_startup() as f32;
   |                  ^^^^^^^^^^^^^^^^^^^^^ method not found in `Res<'_, Time>`

error[E0308]: mismatched types
    --> libs\bevy_shader_utils\examples\voronoise-pan.rs:85:19
     |
85   |             .push("VERTEX_UVS".to_string());
     |              ---- ^^^^^^^^^^^^^^^^^^^^^^^^ expected `ShaderDefVal`, found `String`
     |              |
     |              arguments to this method are incorrect
     |
note: method defined here
    --> C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\src\vec\mod.rs:1836:12
     |
1836 |     pub fn push(&mut self, value: T) {
     |            ^^^^
help: call `Into::into` on this expression to convert `std::string::String` into `ShaderDefVal`
     |
85   |             .push("VERTEX_UVS".to_string().into());
     |                                           +++++++

error[E0308]: mismatched types
    --> libs\bevy_shader_utils\examples\voronoise-pan.rs:88:35
     |
88   |         fragment.shader_defs.push("VERTEX_UVS".to_string());
     |                              ---- ^^^^^^^^^^^^^^^^^^^^^^^^ expected `ShaderDefVal`, found `String`
     |                              |
     |                              arguments to this method are incorrect
     |
note: method defined here
    --> C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\src\vec\mod.rs:1836:12
     |
1836 |     pub fn push(&mut self, value: T) {
     |            ^^^^
help: call `Into::into` on this expression to convert `std::string::String` into `ShaderDefVal`
     |
88   |         fragment.shader_defs.push("VERTEX_UVS".to_string().into());
     |                                                           +++++++

**Comment by ChristopherBiscardi** [comment]
Right now the primary problem with that example is that the shader defs `MAX_CASCADES_PER_LIGHT` and `MAX_DIRECTIONAL_LIGHTS` don't seem to be defined, even though they exist as constants inside of Bevy.

I don't yet understand exactly why that's the case.

```
error: expected expression, found '#'
    ┌─ wgsl:192:41
    │
192 │     cascades: array<DirectionalCascade, #{MAX_CASCADES_PER_LIGHT}>,
    │                                         ^ expected expression
```

**Comment by ChristopherBiscardi** [comment]
That turned out to be very quick! The fix was this one: https://github.com/bevyengine/bevy/issues/7375

**Comment by syapk** [comment]
Greats thanks !!
